//
// AccessDeniedForDependencyException.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The operation you attempted requires you to have the &lt;code&gt;iam:CreateServiceLinkedRole&lt;/code&gt; so that Organizations can create the required service-linked role. You do not have that permission. */

open class AccessDeniedForDependencyException: Codable {

    public var message: ExceptionMessage?
    public var reason: AccessDeniedForDependencyExceptionReason?


    
    public init(message: ExceptionMessage?, reason: AccessDeniedForDependencyExceptionReason?) {
        self.message = message
        self.reason = reason
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(message, forKey: "Message")
        try container.encodeIfPresent(reason, forKey: "Reason")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        message = try container.decodeIfPresent(ExceptionMessage.self, forKey: "Message")
        reason = try container.decodeIfPresent(AccessDeniedForDependencyExceptionReason.self, forKey: "Reason")
    }
}

