//
// AccessDeniedForDependencyExceptionReason.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum AccessDeniedForDependencyExceptionReason: String, Codable {
    case role = "ACCESS_DENIED_DURING_CREATE_SERVICE_LINKED_ROLE"

}
