//
// ActionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ActionType: String, Codable {
    case invite = "INVITE"
    case enableAllFeatures = "ENABLE_ALL_FEATURES"
    case approveAllFeatures = "APPROVE_ALL_FEATURES"
    case addOrganizationsServiceLinkedRole = "ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE"

}
