//
// ChildType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ChildType: String, Codable {
    case account = "ACCOUNT"
    case organizationalUnit = "ORGANIZATIONAL_UNIT"

}
