//
// CreateAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreateAccountRequest: Codable {

    /** The friendly name of the member account. */
    public var accountName: AccountName
    /** The email address of the owner to assign to the new member account. This email address must not already be associated with another AWS account. You must use a valid email address to complete account creation. You cannot access the root user of the account or remove an account that was created with an invalid email address. */
    public var email: Email
    /** &lt;p&gt;If set to &lt;code&gt;ALLOW&lt;/code&gt;, the new account enables IAM users to access account billing information &lt;i&gt;if&lt;/i&gt; they have the required permissions. If set to &lt;code&gt;DENY&lt;/code&gt;, then only the root user of the new account can access account billing information. For more information, see &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/grantaccess.html#ControllingAccessWebsite-Activate\&quot;&gt;Activating Access to the Billing and Cost Management Console&lt;/a&gt; in the &lt;i&gt;AWS Billing and Cost Management User Guide&lt;/i&gt;.&lt;/p&gt; &lt;p&gt;If you do not specify this parameter, the value defaults to ALLOW, and IAM users and roles with the required permissions can access billing information for the new account.&lt;/p&gt; */
    public var iamUserAccessToBilling: IAMUserAccessToBilling?
    /** &lt;p&gt;(Optional)&lt;/p&gt; &lt;p&gt;The name of an IAM role that Organizations automatically preconfigures in the new member account. This role trusts the master account, allowing users in the master account to assume the role, as permitted by the master account administrator. The role has administrator permissions in the new member account.&lt;/p&gt; &lt;p&gt;If you do not specify this parameter, the role name defaults to &lt;code&gt;OrganizationAccountAccessRole&lt;/code&gt;.&lt;/p&gt; &lt;p&gt;For more information about how to use this role to access the member account, see &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html#orgs_manage_accounts_create-cross-account-role\&quot;&gt;Accessing and Administering the Member Accounts in Your Organization&lt;/a&gt; in the &lt;i&gt;AWS Organizations User Guide&lt;/i&gt;, and steps 2 and 3 in &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html\&quot;&gt;Tutorial: Delegate Access Across AWS Accounts Using IAM Roles&lt;/a&gt; in the &lt;i&gt;IAM User Guide&lt;/i&gt;.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; that is used to validate this parameter is a string of characters that can consist of uppercase letters, lowercase letters, digits with no spaces, and any of the following characters: &#x3D;,.@-&lt;/p&gt; */
    public var roleName: RoleName?


    
    public init(accountName: AccountName, email: Email, iamUserAccessToBilling: IAMUserAccessToBilling?, roleName: RoleName?) {
        self.accountName = accountName
        self.email = email
        self.iamUserAccessToBilling = iamUserAccessToBilling
        self.roleName = roleName
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(accountName, forKey: "AccountName")
        try container.encode(email, forKey: "Email")
        try container.encodeIfPresent(iamUserAccessToBilling, forKey: "IamUserAccessToBilling")
        try container.encodeIfPresent(roleName, forKey: "RoleName")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        accountName = try container.decode(AccountName.self, forKey: "AccountName")
        email = try container.decode(Email.self, forKey: "Email")
        iamUserAccessToBilling = try container.decodeIfPresent(IAMUserAccessToBilling.self, forKey: "IamUserAccessToBilling")
        roleName = try container.decodeIfPresent(RoleName.self, forKey: "RoleName")
    }
}

