//
// CreateAccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreateAccountResponse: Codable {

    /** A structure that contains details about the request to create an account. This response structure might not be fully populated when you first receive it because account creation is an asynchronous process. You can pass the returned CreateAccountStatus ID as a parameter to &lt;code&gt; &lt;a&gt;DescribeCreateAccountStatus&lt;/a&gt; &lt;/code&gt; to get status about the progress of the request at later times.  */
    public var createAccountStatus: CreateAccountStatus?


    
    public init(createAccountStatus: CreateAccountStatus?) {
        self.createAccountStatus = createAccountStatus
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(createAccountStatus, forKey: "CreateAccountStatus")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        createAccountStatus = try container.decodeIfPresent(CreateAccountStatus.self, forKey: "CreateAccountStatus")
    }
}

