//
// DeleteOrganizationalUnitRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DeleteOrganizationalUnitRequest: Codable {

    /** &lt;p&gt;The unique identifier (ID) of the organizational unit that you want to delete. You can get the ID from the &lt;a&gt;ListOrganizationalUnitsForParent&lt;/a&gt; operation.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; for an organizational unit ID string requires \&quot;ou-\&quot; followed by from 4 to 32 lower-case letters or digits (the ID of the root that contains the OU) followed by a second \&quot;-\&quot; dash and from 8 to 32 additional lower-case letters or digits.&lt;/p&gt; */
    public var organizationalUnitId: OrganizationalUnitId


    
    public init(organizationalUnitId: OrganizationalUnitId) {
        self.organizationalUnitId = organizationalUnitId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(organizationalUnitId, forKey: "OrganizationalUnitId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        organizationalUnitId = try container.decode(OrganizationalUnitId.self, forKey: "OrganizationalUnitId")
    }
}

