//
// DeletePolicyRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DeletePolicyRequest: Codable {

    /** &lt;p&gt;The unique identifier (ID) of the policy that you want to delete. You can get the ID from the &lt;a&gt;ListPolicies&lt;/a&gt; or &lt;a&gt;ListPoliciesForTarget&lt;/a&gt; operations.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; for a policy ID string requires \&quot;p-\&quot; followed by from 8 to 128 lower-case letters or digits.&lt;/p&gt; */
    public var policyId: PolicyId


    
    public init(policyId: PolicyId) {
        self.policyId = policyId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(policyId, forKey: "PolicyId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        policyId = try container.decode(PolicyId.self, forKey: "PolicyId")
    }
}

