//
// DescribeCreateAccountStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DescribeCreateAccountStatusResponse: Codable {

    /** A structure that contains the current status of an account creation request. */
    public var createAccountStatus: CreateAccountStatus?


    
    public init(createAccountStatus: CreateAccountStatus?) {
        self.createAccountStatus = createAccountStatus
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(createAccountStatus, forKey: "CreateAccountStatus")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        createAccountStatus = try container.decodeIfPresent(CreateAccountStatus.self, forKey: "CreateAccountStatus")
    }
}

