//
// DisableAWSServiceAccessRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DisableAWSServiceAccessRequest: Codable {

    /** The service principal name of the AWS service for which you want to disable integration with your organization. This is typically in the form of a URL, such as &lt;code&gt; &lt;i&gt;service-abbreviation&lt;/i&gt;.amazonaws.com&lt;/code&gt;. */
    public var servicePrincipal: ServicePrincipal


    
    public init(servicePrincipal: ServicePrincipal) {
        self.servicePrincipal = servicePrincipal
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(servicePrincipal, forKey: "ServicePrincipal")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        servicePrincipal = try container.decode(ServicePrincipal.self, forKey: "ServicePrincipal")
    }
}

