//
// EnabledServicePrincipal.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A structure that contains details of a service principal that is enabled to integrate with AWS Organizations. */

open class EnabledServicePrincipal: Codable {

    /** The date that the service principal was enabled for integration with AWS Organizations. */
    public var dateEnabled: Timestamp?
    /** The name of the service principal. This is typically in the form of a URL, such as: &lt;code&gt; &lt;i&gt;servicename&lt;/i&gt;.amazonaws.com&lt;/code&gt;. */
    public var servicePrincipal: ServicePrincipal?


    
    public init(dateEnabled: Timestamp?, servicePrincipal: ServicePrincipal?) {
        self.dateEnabled = dateEnabled
        self.servicePrincipal = servicePrincipal
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(dateEnabled, forKey: "DateEnabled")
        try container.encodeIfPresent(servicePrincipal, forKey: "ServicePrincipal")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        dateEnabled = try container.decodeIfPresent(Timestamp.self, forKey: "DateEnabled")
        servicePrincipal = try container.decodeIfPresent(ServicePrincipal.self, forKey: "ServicePrincipal")
    }
}

