//
// EnablePolicyTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class EnablePolicyTypeResponse: Codable {

    /** A structure that shows the root with the updated list of enabled policy types. */
    public var root: Root?


    
    public init(root: Root?) {
        self.root = root
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(root, forKey: "Root")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        root = try container.decodeIfPresent(Root.self, forKey: "Root")
    }
}

