//
// HandshakeState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum HandshakeState: String, Codable {
    case requested = "REQUESTED"
    case open = "OPEN"
    case canceled = "CANCELED"
    case accepted = "ACCEPTED"
    case declined = "DECLINED"
    case expired = "EXPIRED"

}
