//
// HandshakeConstraintViolationExceptionReason.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum HandshakeConstraintViolationExceptionReason: String, Codable {
    case accountNumberLimitExceeded = "ACCOUNT_NUMBER_LIMIT_EXCEEDED"
    case handshakeRateLimitExceeded = "HANDSHAKE_RATE_LIMIT_EXCEEDED"
    case alreadyInAnOrganization = "ALREADY_IN_AN_ORGANIZATION"
    case organizationAlreadyHasAllFeatures = "ORGANIZATION_ALREADY_HAS_ALL_FEATURES"
    case inviteDisabledDuringEnableAllFeatures = "INVITE_DISABLED_DURING_ENABLE_ALL_FEATURES"
    case paymentInstrumentRequired = "PAYMENT_INSTRUMENT_REQUIRED"
    case organizationFromDifferentSellerOfRecord = "ORGANIZATION_FROM_DIFFERENT_SELLER_OF_RECORD"
    case organizationMembershipChangeRateLimitExceeded = "ORGANIZATION_MEMBERSHIP_CHANGE_RATE_LIMIT_EXCEEDED"

}
