//
// HandshakeResourceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum HandshakeResourceType: String, Codable {
    case account = "ACCOUNT"
    case organization = "ORGANIZATION"
    case organizationFeatureSet = "ORGANIZATION_FEATURE_SET"
    case email = "EMAIL"
    case masterEmail = "MASTER_EMAIL"
    case masterName = "MASTER_NAME"
    case notes = "NOTES"
    case parentHandshake = "PARENT_HANDSHAKE"

}
