//
// InvalidInputExceptionReason.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum InvalidInputExceptionReason: String, Codable {
    case invalidPartyTypeTarget = "INVALID_PARTY_TYPE_TARGET"
    case invalidSyntaxOrganizationArn = "INVALID_SYNTAX_ORGANIZATION_ARN"
    case invalidSyntaxPolicyId = "INVALID_SYNTAX_POLICY_ID"
    case invalidEnum = "INVALID_ENUM"
    case invalidListMember = "INVALID_LIST_MEMBER"
    case maxLengthExceeded = "MAX_LENGTH_EXCEEDED"
    case maxValueExceeded = "MAX_VALUE_EXCEEDED"
    case minLengthExceeded = "MIN_LENGTH_EXCEEDED"
    case minValueExceeded = "MIN_VALUE_EXCEEDED"
    case immutablePolicy = "IMMUTABLE_POLICY"
    case invalidPattern = "INVALID_PATTERN"
    case invalidPatternTargetId = "INVALID_PATTERN_TARGET_ID"
    case inputRequired = "INPUT_REQUIRED"
    case invalidNextToken = "INVALID_NEXT_TOKEN"
    case maxLimitExceededFilter = "MAX_LIMIT_EXCEEDED_FILTER"
    case movingAccountBetweenDifferentRoots = "MOVING_ACCOUNT_BETWEEN_DIFFERENT_ROOTS"
    case invalidFullNameTarget = "INVALID_FULL_NAME_TARGET"
    case unrecognizedServicePrincipal = "UNRECOGNIZED_SERVICE_PRINCIPAL"
    case invalidRoleName = "INVALID_ROLE_NAME"

}
