//
// ListParentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListParentsResponse: Codable {

    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?
    /** A list of parents for the specified child account or OU. */
    public var parents: Parents?


    
    public init(nextToken: NextToken?, parents: Parents?) {
        self.nextToken = nextToken
        self.parents = parents
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(nextToken, forKey: "NextToken")
        try container.encodeIfPresent(parents, forKey: "Parents")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
        parents = try container.decodeIfPresent(Parents.self, forKey: "Parents")
    }
}

