//
// ListAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListAccountsResponse: Codable {

    /** A list of objects in the organization. */
    public var accounts: Accounts?
    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?


    
    public init(accounts: Accounts?, nextToken: NextToken?) {
        self.accounts = accounts
        self.nextToken = nextToken
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(accounts, forKey: "Accounts")
        try container.encodeIfPresent(nextToken, forKey: "NextToken")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        accounts = try container.decodeIfPresent(Accounts.self, forKey: "Accounts")
        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
    }
}

