//
// ListOrganizationalUnitsForParentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListOrganizationalUnitsForParentResponse: Codable {

    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?
    /** A list of the OUs in the specified root or parent OU. */
    public var organizationalUnits: OrganizationalUnits?


    
    public init(nextToken: NextToken?, organizationalUnits: OrganizationalUnits?) {
        self.nextToken = nextToken
        self.organizationalUnits = organizationalUnits
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(nextToken, forKey: "NextToken")
        try container.encodeIfPresent(organizationalUnits, forKey: "OrganizationalUnits")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
        organizationalUnits = try container.decodeIfPresent(OrganizationalUnits.self, forKey: "OrganizationalUnits")
    }
}

