//
// ListHandshakesForAccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListHandshakesForAccountResponse: Codable {

    /** A list of &lt;a&gt;Handshake&lt;/a&gt; objects with details about each of the handshakes that is associated with the specified account. */
    public var handshakes: Handshakes?
    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?


    
    public init(handshakes: Handshakes?, nextToken: NextToken?) {
        self.handshakes = handshakes
        self.nextToken = nextToken
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(handshakes, forKey: "Handshakes")
        try container.encodeIfPresent(nextToken, forKey: "NextToken")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        handshakes = try container.decodeIfPresent(Handshakes.self, forKey: "Handshakes")
        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
    }
}

