//
// ListPoliciesForTargetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListPoliciesForTargetResponse: Codable {

    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?
    /** The list of policies that match the criteria in the request. */
    public var policies: Policies?


    
    public init(nextToken: NextToken?, policies: Policies?) {
        self.nextToken = nextToken
        self.policies = policies
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(nextToken, forKey: "NextToken")
        try container.encodeIfPresent(policies, forKey: "Policies")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
        policies = try container.decodeIfPresent(Policies.self, forKey: "Policies")
    }
}

