//
// ListCreateAccountStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListCreateAccountStatusResponse: Codable {

    /** A list of objects with details about the requests. Certain elements, such as the accountId number, are present in the output only after the account has been successfully created. */
    public var createAccountStatuses: CreateAccountStatuses?
    /** If present, this value indicates that there is more output available than is included in the current response. Use this value in the &lt;code&gt;NextToken&lt;/code&gt; request parameter in a subsequent call to the operation to get the next part of the output. You should repeat this until the &lt;code&gt;NextToken&lt;/code&gt; response element comes back as &lt;code&gt;null&lt;/code&gt;. */
    public var nextToken: NextToken?


    
    public init(createAccountStatuses: CreateAccountStatuses?, nextToken: NextToken?) {
        self.createAccountStatuses = createAccountStatuses
        self.nextToken = nextToken
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(createAccountStatuses, forKey: "CreateAccountStatuses")
        try container.encodeIfPresent(nextToken, forKey: "NextToken")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        createAccountStatuses = try container.decodeIfPresent(CreateAccountStatuses.self, forKey: "CreateAccountStatuses")
        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
    }
}

