//
// ListChildrenRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListChildrenRequest: Codable {

    /** Filters the output to include only the specified child type. */
    public var childType: ChildType
    /** (Optional) Use this to limit the number of results you want included in the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the maximum you specify, the &lt;code&gt;NextToken&lt;/code&gt; response element is present and has a value (is not null). Include that value as the &lt;code&gt;NextToken&lt;/code&gt; request parameter in the next call to the operation to get the next part of the results. Note that Organizations might return fewer results than the maximum even when there are more results available. You should check &lt;code&gt;NextToken&lt;/code&gt; after every operation to ensure that you receive all of the results. */
    public var maxResults: MaxResults?
    /** Use this parameter if you receive a &lt;code&gt;NextToken&lt;/code&gt; response in a previous request that indicates that there is more output available. Set it to the value of the previous call&#39;s &lt;code&gt;NextToken&lt;/code&gt; response to indicate where the output should continue from. */
    public var nextToken: NextToken?
    /** &lt;p&gt;The unique identifier (ID) for the parent root or OU whose children you want to list.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; for a parent ID string requires one of the following:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;Root: a string that begins with \&quot;r-\&quot; followed by from 4 to 32 lower-case letters or digits.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;Organizational unit (OU): a string that begins with \&quot;ou-\&quot; followed by from 4 to 32 lower-case letters or digits (the ID of the root that the OU is in) followed by a second \&quot;-\&quot; dash and from 8 to 32 additional lower-case letters or digits.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt; */
    public var parentId: ParentId


    
    public init(childType: ChildType, maxResults: MaxResults?, nextToken: NextToken?, parentId: ParentId) {
        self.childType = childType
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.parentId = parentId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(childType, forKey: "ChildType")
        try container.encodeIfPresent(maxResults, forKey: "MaxResults")
        try container.encodeIfPresent(nextToken, forKey: "NextToken")
        try container.encode(parentId, forKey: "ParentId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        childType = try container.decode(ChildType.self, forKey: "ChildType")
        maxResults = try container.decodeIfPresent(MaxResults.self, forKey: "MaxResults")
        nextToken = try container.decodeIfPresent(NextToken.self, forKey: "NextToken")
        parentId = try container.decode(ParentId.self, forKey: "ParentId")
    }
}

