//
// OrganizationFeatureSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum OrganizationFeatureSet: String, Codable {
    case all = "ALL"
    case consolidatedBilling = "CONSOLIDATED_BILLING"

}
