//
// ParentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ParentType: String, Codable {
    case root = "ROOT"
    case organizationalUnit = "ORGANIZATIONAL_UNIT"

}
