//
// PolicyTypeStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum PolicyTypeStatus: String, Codable {
    case enabled = "ENABLED"
    case pendingEnable = "PENDING_ENABLE"
    case pendingDisable = "PENDING_DISABLE"

}
