//
// PolicyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum PolicyType: String, Codable {
    case policy = "SERVICE_CONTROL_POLICY"

}
