//
// Root.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details about a root. A root is a top-level parent node in the hierarchy of an organization that can contain organizational units (OUs) and accounts. Every root contains every AWS account in the organization. Each root enables the accounts to be organized in a different way and to have different policy types enabled for use in that root. */

open class Root: Codable {

    /** &lt;p&gt;The Amazon Resource Name (ARN) of the root.&lt;/p&gt; &lt;p&gt;For more information about ARNs in Organizations, see &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/organizations/latest/userguide/orgs_permissions.html#orgs-permissions-arns\&quot;&gt;ARN Formats Supported by Organizations&lt;/a&gt; in the &lt;i&gt;AWS Organizations User Guide&lt;/i&gt;.&lt;/p&gt; */
    public var arn: RootArn?
    /** &lt;p&gt;The unique identifier (ID) for the root.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; for a root ID string requires \&quot;r-\&quot; followed by from 4 to 32 lower-case letters or digits.&lt;/p&gt; */
    public var id: RootId?
    /** &lt;p&gt;The friendly name of the root.&lt;/p&gt; &lt;p&gt;The &lt;a href&#x3D;\&quot;http://wikipedia.org/wiki/regex\&quot;&gt;regex pattern&lt;/a&gt; that is used to validate this parameter is a string of any of the characters in the ASCII character range.&lt;/p&gt; */
    public var name: RootName?
    /** &lt;p&gt;The types of policies that are currently enabled for the root and therefore can be attached to the root or to its OUs or accounts.&lt;/p&gt; &lt;note&gt; &lt;p&gt;Even if a policy type is shown as available in the organization, you can separately enable and disable them at the root level by using &lt;a&gt;EnablePolicyType&lt;/a&gt; and &lt;a&gt;DisablePolicyType&lt;/a&gt;. Use &lt;a&gt;DescribeOrganization&lt;/a&gt; to see the availability of the policy types in that organization.&lt;/p&gt; &lt;/note&gt; */
    public var policyTypes: PolicyTypes?


    
    public init(arn: RootArn?, id: RootId?, name: RootName?, policyTypes: PolicyTypes?) {
        self.arn = arn
        self.id = id
        self.name = name
        self.policyTypes = policyTypes
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(arn, forKey: "Arn")
        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(policyTypes, forKey: "PolicyTypes")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        arn = try container.decodeIfPresent(RootArn.self, forKey: "Arn")
        id = try container.decodeIfPresent(RootId.self, forKey: "Id")
        name = try container.decodeIfPresent(RootName.self, forKey: "Name")
        policyTypes = try container.decodeIfPresent(PolicyTypes.self, forKey: "PolicyTypes")
    }
}

