//
// TargetType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TargetType: String, Codable {
    case account = "ACCOUNT"
    case organizationalUnit = "ORGANIZATIONAL_UNIT"
    case root = "ROOT"

}
