//
// UpdatePolicyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class UpdatePolicyResponse: Codable {

    /** A structure that contains details about the updated policy, showing the requested changes. */
    public var policy: Policy?


    
    public init(policy: Policy?) {
        self.policy = policy
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(policy, forKey: "Policy")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        policy = try container.decodeIfPresent(Policy.self, forKey: "Policy")
    }
}

